2025-08-25 11:58:01,892 | INFO | app.main | Iniciando carga...
2025-08-25 11:58:01,893 | INFO | app.main | Carregando cadastros de: data/bairros.json
2025-08-25 11:58:01,966 | ERROR | app.main | Falha na execução: Error processing data/bairros.json: This transaction is inactive
Traceback (most recent call last):
  File "C:\Users\Tributech\Downloads\Escriptes\aux-clevelandia\aux-clevelandia\app\loader.py", line 90, in processar_cadastros
    loader = _determine_loader(data, json_path)
  File "C:\Users\Tributech\Downloads\Escriptes\aux-clevelandia\aux-clevelandia\app\loader.py", line 51, in _determine_loader
    processar_cadastros_from_bairros(json_path)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Tributech\Downloads\Escriptes\aux-clevelandia\aux-clevelandia\app\loader_municipio.py", line 141, in processar_cadastros_from_bairros
    sess.commit()
    ~~~~~~~~~~~^^
  File "C:\Users\Tributech\Downloads\Escriptes\aux-clevelandia\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\Tributech\Downloads\Escriptes\aux-clevelandia\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Tributech\Downloads\Escriptes\aux-clevelandia\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1320, in commit
    trans.commit()
    ~~~~~~~~~~~~^^
  File "C:\Users\Tributech\Downloads\Escriptes\aux-clevelandia\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2632, in commit
    self._do_commit()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Tributech\Downloads\Escriptes\aux-clevelandia\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2755, in _do_commit
    raise exc.InvalidRequestError("This transaction is inactive")
sqlalchemy.exc.InvalidRequestError: This transaction is inactive

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tributech\Downloads\Escriptes\aux-clevelandia\aux-clevelandia\app\main.py", line 199, in main
    cadastro_loader(session, args.json)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tributech\Downloads\Escriptes\aux-clevelandia\aux-clevelandia\app\loader.py", line 103, in processar_cadastros
    raise ValueError(f"Error processing {json_path}: {str(e)}")
ValueError: Error processing data/bairros.json: This transaction is inactive
2025-08-25 11:58:01,975 | INFO | app.main | Finalizado em 0.08s.
